---
name: Docker image build and push

on:
  push:
    branches:
      - master
  pull_request:
    
jobs:
  build-image:
    name: Build gcp-backend image
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: ${{ github.event_name != 'pull_request' }}
          # Frontend and backend images are under the same private repository; no 'latest' tag is assigned.
          # to get respective latest image :frontend or :backend is to be used
          tags: |
            ${{ secrets.DOCKERHUB_LOGIN }}/${{ vars.DOCKERHUB_IMAGE_NAME }}:${{ vars.IMAGE_TAG }}
            ${{ secrets.DOCKERHUB_LOGIN }}/${{ vars.DOCKERHUB_IMAGE_NAME }}:${{ VARS.IMAGE_TAG }}-${{ github.sha }}